<?php

/**
 * @file
 * Allows you to edit the configuration related to Contextual Links.
 *
 * Created by: Topsitemakers
 * http://www.topsitemakers.com/
 */

/**
 * Implements hook_menu().
 */
function contextual_hide_menu() {
  $items['admin/config/user-interface/contextual-config'] = array(
    'title' => 'Contextual Links Configuration',
    'description' => 'Change Contextual Links configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('contextual_hide_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'contextual_hide.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_contextual_links_view_alter().
 */
function contextual_hide_contextual_links_view_alter(&$element, $items) {
  // Get the list of entities for which the contextual links should be disabled.
  //
  // There probably could be a more optimized way to do this, but for now it can
  // stay this way.
  $entities = variable_get('contextual_hide_contextual_links_entities', array());

  // Unfortunately, there is no consistent way to check the parent entity.
  if (
    // Views.
    (isset($entities['views']) && $entities['views'] && isset($element['#element']['#views_contextual_links_info'])) ||
    // Blocks.
    (isset($entities['block']) && $entities['block'] && isset($element['#element']['#block'])) ||
    // Nodes.
    (isset($entities['nodes']) && $entities['nodes'] && isset($element['#element']['#node']))
  ) {
    unset($element['#links']);
  }
}
